"""
Author: M. P Schneider
Affiliation: Cancer Research UK, CI
Program: Workflow for single cell or sWGS DNAseq absolute copy number calling - unknown ploidy
Date: April 2020
"""
import pandas as pd
import os

configfile: "config/config.yaml"
assert(isinstance(config["binSize"], int))
df = pd.read_csv(config["samples"], sep="\t", dtype={"sample_name": str})
if len(df.columns) == 1:
    SAMPLE_FILES = df.iloc[:, 0].tolist()
else:
    SAMPLE_FILES = df["sample_name"].tolist()

f = lambda st : st[:-4] if st.endswith('.bam') else st
SAMPLE_FILES = [f(s) for s in SAMPLE_FILES]
IMAGE = config["scAbsolute_img"]


def helper_dirname(wildcards):
    filename = str(config["sampleName"])+"_"+str(config["binSize"])+".rds"
    return os.path.join("results", str(config["binSize"]), filename)


include: "rules/qc.smk"
include: "rules/density.smk"
include: "rules/scale_scAbsolute.smk"
include: "rules/combine.smk"

ruleorder: qc > density > scale_scAbsolute > combine


rule all:
    input:
        helper_dirname
