samples: config/PEO1_subset.tsv #sample_PEO4.tsv sample_PEO1.tsv
##samples: config/samples_trial_human.tsv ##config/samples_trial_mouse.tsv
sampleName: PEO1_subset # PEO4/1 Trial_Human
binSize: 500 ## single value only - see documentation for valid bin size values
species: Human ##Mouse
genome: hg19 ##GRCm38 (we do not recommend using Human hg38, as the QC has not been optimized for this genome build, due to limited data availability
estimateReadDensity : False # flag to include read density estimation for detection of WGD
# requires additional memory, only useful in cases where WGD is suspected
scAbsolute_img: "docker://glaux1126/scabsolute:v3.8.0"
scUnique_img: "docker://glaux1126/scunique:v2.2.2"
qc_img: "docker://public.ecr.aws/k5n6p8b3/biocontainers/samtools:v1.9-4deb_cv1"
NCORES: 12
