samples: config/samples.tsv
binSize: 500 # single value only, required
scAbsolute_img: "docker://770395835384.dkr.ecr.eu-central-1.amazonaws.com/scabsolute:v2.9.4"
qc_img: "docker://public.ecr.aws/k5n6p8b3/biocontainers/samtools:v1.9-4-deb_cv1"
