samples: config/samples_trial_human.tsv ##config/samples_trial_mouse.tsv
binSize: 500 # single value only, required
scAbsolute_img: "docker://public.ecr.aws/k5n6p8b3/scabsolute:v3.7.2"
qc_img: "docker://public.ecr.aws/k5n6p8b3/biocontainers/samtools:v1.9-4deb_cv1"
species: Human ##Mouse
genome: hg19 ##GRCm38